[0m10:58:35.752162 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103a3e4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104a23130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104a22a10>]}


============================== 10:58:35.760981 | d8a107f3-0f92-4be3-992c-1f45417f0b2b ==============================
[0m10:58:35.760981 [info ] [MainThread]: Running with dbt=1.9.0
[0m10:58:35.761305 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '.', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m10:59:05.731959 [debug] [MainThread]: Starter project path: /Users/patricia.carmona/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dbt/include/starter_project
[0m10:59:05.781777 [info ] [MainThread]: 
Your new dbt project "dbt_fusion_poc" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:59:05.782626 [info ] [MainThread]: Setting up your profile.
[0m10:59:05.783880 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m10:59:05.802812 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 30.156742, "process_in_blocks": "0", "process_kernel_time": 0.672611, "process_mem_max_rss": "102121472", "process_out_blocks": "0", "process_user_time": 1.748593}
[0m10:59:05.803456 [debug] [MainThread]: Command `dbt init` failed at 10:59:05.803261 after 30.16 seconds
[0m10:59:05.804541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103a3e4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104a23af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104a22320>]}
[0m10:59:05.805578 [debug] [MainThread]: Flushing usage events
[0m10:59:06.325272 [debug] [MainThread]: An error was encountered while trying to flush usage events
